apiVersion: v1
kind: ConfigMap
metadata:
  name: vacciguard-pipeline-hot
data:
  APP_NAME: vacciguard-stream-processor
  KAFKA_TOPIC: vacciguard-telemetry
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  REDIS_HOST: vacciguard-baseline-redis.ntns1o.0001.aps1.cache.amazonaws.com
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  KAFKA_CONSUMER_GROUP_ID: vacciguard-pipeline-hot
  KAFKA_STARTING_OFFSETS: earliest
  MAX_OFFSETS_PER_TRIGGER: "1000"
  TRIGGER_INTERVAL: 5 seconds
  WATERMARK_DELAY: 10 minutes
  PIPELINE_MODE: baseline
