apiVersion: batch/v1
kind: Job
metadata:
  name: evaluation-controller
spec:
  suspend: true
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: evaluation-controller
      restartPolicy: Never
      containers:
        - name: evaluation-controller
          image: 347038623570.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-evaluation-controller:split-optimized-20260417t170754z-amd64
          imagePullPolicy: Always
          env:
            - name: PIPELINE_TARGET
              value: baseline
            - name: SCENARIO
              value: normal
            - name: RUN_ID
              value: run-001
            - name: WORKLOAD_FAMILY_VERSION
              value: evaluation-workload-v1
            - name: S3_BUCKET_NAME
              value: vacciguard-baseline-893721683785-data
            - name: EVALUATION_CONTROLLER_MODE
              value: orchestrate
            - name: PIPELINE_CONFIG_NAME
              value: vacciguard-pipeline-config
            - name: REPLAY_IMAGE
              value: 893721683785.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-minimal-replay-producer:aws-deploy-20260622t081349z-amd64
