apiVersion: batch/v1
kind: Job
metadata:
  name: replay-producer
spec:
  template:
    spec:
      serviceAccountName: vacciguard-pipeline
      restartPolicy: Never
      containers:
        - name: replay-producer
          image: 347038623570.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-replay-producer:baseline
          imagePullPolicy: Always
          volumeMounts:
            - name: workload-dev
              mountPath: /data/workloads/dev
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: KAFKA_TOPIC
              value: vacciguard-telemetry
            - name: WORKLOAD_FILE
              value: /data/workloads/dev/events.ndjson
            - name: EVENTS_PER_SECOND
              value: "5"
            - name: LOOP
              value: "false"
      volumes:
        - name: workload-dev
          configMap:
            name: vacciguard-workload-dev
