apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vacciguard
resources:
  - namespace.yaml
  - serviceaccount-pipeline.yaml
  - configmap-pipeline.yaml
  - configmap-lookup.yaml
  - configmap-workload-dev.yaml
  - service-kafka.yaml
  - statefulset-kafka.yaml
  - deployment-stream-processor.yaml
  - job-replay-producer.yaml
