apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vacciguard
resources:
  - namespace.yaml
  - serviceaccount-pipeline.yaml
  - serviceaccount-evaluation-controller.yaml
  - configmap-pipeline.yaml
  - configmap-pipeline-compat.yaml
  - configmap-pipeline-archive.yaml
  - configmap-lookup.yaml
  - configmap-workload-dev.yaml
  - role-evaluation-controller.yaml
  - rolebinding-evaluation-controller.yaml
  - service-kafka.yaml
  - statefulset-kafka.yaml
  - deployment-stream-processor.yaml
  - job-replay-producer.yaml
  - job-evaluation-controller.yaml
images:
  - name: 347038623570.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-stream-processor
    newName: 893721683785.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-stream-processor
    newTag: aws-deploy-20260622t081349z-amd64
  - name: 347038623570.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-minimal-replay-producer
    newName: 893721683785.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-minimal-replay-producer
    newTag: aws-deploy-20260622t081349z-amd64
  - name: 347038623570.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-evaluation-controller
    newName: 893721683785.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-evaluation-controller
    newTag: aws-deploy-20260622t081349z-amd64
