apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-config
  namespace: observability
data:
  AWS_REGION: ap-south-1
  AMP_REMOTE_WRITE_ENDPOINT: https://aps-workspaces.ap-south-1.amazonaws.com/workspaces/REPLACE_ME/api/v1/remote_write
  config.yaml: |
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s
          scrape_configs:
            - job_name: stream-processor-metrics
              metrics_path: /metrics
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_namespace]
                  action: keep
                  regex: vacciguard
                - source_labels: [__meta_kubernetes_pod_phase]
                  action: keep
                  regex: Running
                - source_labels: [__meta_kubernetes_pod_container_port_name]
                  action: keep
                  regex: metrics
                - source_labels: [__meta_kubernetes_pod_label_app]
                  action: keep
                  regex: stream-processor
                - source_labels: [__meta_kubernetes_pod_label_pipeline_target]
                  target_label: pipeline_target
                - source_labels: [__meta_kubernetes_pod_name]
                  target_label: pod
            - job_name: replay-producer-metrics
              metrics_path: /metrics
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_namespace]
                  action: keep
                  regex: vacciguard
                - source_labels: [__meta_kubernetes_pod_phase]
                  action: keep
                  regex: Running
                - source_labels: [__meta_kubernetes_pod_container_port_name]
                  action: keep
                  regex: metrics
                - source_labels: [__meta_kubernetes_pod_label_job_name]
                  action: keep
                  regex: replay-producer
                - source_labels: [__meta_kubernetes_pod_label_pipeline_target]
                  target_label: pipeline_target
                - source_labels: [__meta_kubernetes_pod_name]
                  target_label: pod

    processors:
      batch:
        timeout: 5s
        send_batch_size: 1024

    exporters:
      awsprometheusremotewrite:
        endpoint: ${env:AMP_REMOTE_WRITE_ENDPOINT}
        auth:
          authenticator: sigv4auth

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      sigv4auth:
        region: ${env:AWS_REGION}

    service:
      extensions: [health_check, sigv4auth]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [awsprometheusremotewrite]
