apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - serviceaccount-adot-collector.yaml
  - role-adot-collector.yaml
  - rolebinding-adot-collector.yaml
  - configmap-collector.yaml
  - service-collector.yaml
  - deployment-adot-collector.yaml
