apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: observability
  # IRSA subject: system:serviceaccount:observability:adot-collector
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::347038623570:role/vacciguard-baseline-observability-adot-collector
