apiVersion: v1
kind: ConfigMap
metadata:
  name: vacciguard-pipeline-config
data:
  PROCESSED_OUTPUT_PATH: s3a://vacciguard-aayush-baseline-data-347038623570/processed
  INVALID_OUTPUT_PATH: s3a://vacciguard-aayush-baseline-data-347038623570/invalid
  CHECKPOINT_ROOT: s3a://vacciguard-aayush-baseline-data-347038623570/checkpoints
  BREACH_WINDOW_OUTPUT_PATH: s3a://vacciguard-aayush-baseline-data-347038623570/breach_windows
  REDIS_HOST: vacciguard-aayush-baseline-redis.jhlect.0001.aps1.cache.amazonaws.com
  KAFKA_TOPIC_PARTITIONS: "6"
  SPARK_SQL_SHUFFLE_PARTITIONS: "6"
  SPARK_DEFAULT_PARALLELISM: "6"
