apiVersion: v1
kind: ConfigMap
metadata:
  name: vacciguard-pipeline-config
data:
  PROCESSED_OUTPUT_PATH: s3a://vacciguard-tanish-baseline-ap-south-1-data/processed
  INVALID_OUTPUT_PATH: s3a://vacciguard-tanish-baseline-ap-south-1-data/invalid
  CHECKPOINT_ROOT: s3a://vacciguard-tanish-baseline-ap-south-1-data/checkpoints
  BREACH_WINDOW_OUTPUT_PATH: s3a://vacciguard-tanish-baseline-ap-south-1-data/breach_windows
  REDIS_HOST: vacciguard-tanish-baseline-redis.jhlect.0001.aps1.cache.amazonaws.com
  KAFKA_TOPIC_PARTITIONS: "6"
  SPARK_SQL_SHUFFLE_PARTITIONS: "6"
  SPARK_DEFAULT_PARALLELISM: "6"
