apiVersion: batch/v1
kind: Job
metadata:
  name: replay-producer
spec:
  template:
    spec:
      containers:
        - name: replay-producer
          image: 347038623570.dkr.ecr.ap-south-1.amazonaws.com/vacciguard-tanish-baseline-replay-producer:dev-local
