apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::347038623570:role/vacciguard-tanish-baseline-evaluation-controller-irsa-role
