apiVersion: v1
kind: ConfigMap
metadata:
  name: vacciguard-pipeline-config
  namespace: vacciguard
data:
  PIPELINE_MODE: optimized
  TRIGGER_INTERVAL: 1 seconds
  WATERMARK_DELAY: 30 seconds
  CHECKPOINT_ROOT: /data/checkpoints
