apiVersion: v1
kind: ConfigMap
metadata:
  name: vacciguard-pipeline-config-cold
  namespace: vacciguard
data:
  PIPELINE_MODE: optimized
  PIPELINE_SERVICE_ROLE: cold
  COLD_TRIGGER_INTERVAL: 30 seconds
  CHECKPOINT_ROOT: /data/checkpoints/cold
