apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../baseline
patches:
  - path: configmap-pipeline.yaml
  - path: patch-kafka-resources.yaml
  - path: patch-stream-processor-resources.yaml
