apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-processor-cold
  namespace: vacciguard
spec:
  template:
    spec:
      containers:
        - name: stream-processor
          resources:
            requests:
              cpu: "400m"
              memory: "2048Mi"
            limits:
              cpu: "1500m"
              memory: "3072Mi"
